# this dockerfile is used for application and for environment

# start with a base image
FROM node:alpine 

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .
# 把当前所有的内容拷贝到docker下面

CMD ["npm", "run", "start"]



