# specify a base image

FROM node:alpine

# install some dependencies
# use alpine as a base image, alpine is a very small image, program included in alpine is very limited
# refer to docker hub
COPY ./ ./
RUN npm install

# default command

CMD ["npm", "start"]

# first show npm not found 

# set a port mapping 

